import random
import turtle
import math
while 1:
    r=random.randint (10,100)
    x=random.randint (-350,350)
    y=random.randint (-350,350)
    m=random.randint (0,360)
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.right (m)
    turtle.fillcolor('white')
    turtle.begin_fill()
    turtle.circle(r,180)
    turtle.end_fill()
    turtle.fillcolor('black')
    turtle.begin_fill()
    turtle.circle(r,180)
    turtle.end_fill()
    turtle.begin_fill()
    turtle.circle(r*0.5,180)
    turtle.end_fill()
    turtle.right (180)
    turtle.fillcolor('white')
    turtle.begin_fill()
    turtle.circle(r*0.5,-180)
    turtle.end_fill()
    turtle.penup()
    turtle.left(90)
    turtle.forward(r*0.4)
    turtle.right(90)
    turtle.fillcolor('black')
    turtle.begin_fill()
    turtle.circle(r*0.1)
    turtle.end_fill()
    turtle.left(90)
    turtle.penup()
    turtle.forward(r)
    turtle.right(90)
    turtle.fillcolor('white')
    turtle.begin_fill()
    turtle.circle(r*0.1)
    turtle.end_fill()
    
