#李国威
#222017321102066
import turtle
turtle.circle (100,180)
turtle.fillcolor ('black')
turtle.begin_fill ()
turtle.circle (100,180)
turtle.end_fill()
turtle.begin_fill ()
turtle.circle (50,180)
turtle.end_fill ()
turtle.fillcolor ('white')
turtle.begin_fill ()
turtle.penup()
turtle.goto(0,200)
turtle.pendown ()
turtle.circle (50,180)
turtle.end_fill ()
turtle.penup ()
turtle.goto(0,40)
turtle.pendown()
turtle.begin_fill ()
turtle.circle (10)
turtle.end_fill ()
turtle.fillcolor ('black')
turtle.penup()
turtle.goto(0,140)
turtle.begin_fill ()
turtle.circle (10)
turtle.end_fill() 
turtle.penup()
turtle.goto (0,-50)
turtle.pendown()
