//
// Created by god on 2021/12/25.
//

#ifndef TRAFFIC_INFORMATION_SYSTEM_TRAIN_WINDOW_H
#define TRAFFIC_INFORMATION_SYSTEM_TRAIN_WINDOW_H

#include "header/common.h"
#endif //TRAFFIC_INFORMATION_SYSTEM_TRAIN_WINDOW_H
